Feat : add French Translations
bolt/core pull request #1903
Opened 2020-09-24 15:06 UTC by BoutValentin

Change the french translation in the translations folder to provide full translate

2020-09-24 15:16 UTC, toofff requested changes

2020-09-24 15:16 UTC, toofff commented on translations/validators.fr.xlf
> +  <file id="validators.en">
`<file id="validators.fr">`

2020-09-24 15:16 UTC, toofff commented on translations/security.fr.xlf
> +  <file id="security.en">
`<file id="security.fr">`

2020-09-24 15:16 UTC, toofff commented on translations/messages.fr.xlf
> +  <file id="messages.en">
`<file id="messages.fr">`

2020-09-25 07:18 UTC, bobdenotter approved these changes
Merci beaucoup, @BoutValentin et @toofff 👍

2020-09-25 08:12 UTC, toofff commented
@bobdenotter il nous reste encore un peu de relecture à faire, j'espère que l'on aura tout corrigé aujourd'hui ;)

2020-09-25 08:18 UTC, bobdenotter commented
Je vais laisser le PR ouvert pour le moment. Faites-moi savoir quand vous avez terminé! :-)

2020-09-25 12:36 UTC, toofff approved these changes

2020-09-25 12:37 UTC, toofff commented
@bobdenotter C'est bon pour nous, avec @BoutValentin nous avons relu et corrigé ce midi.

Merci pour l'attente ;)

2020-09-27 07:27 UTC, bobdenotter commented
Thank again, @BoutValentin and @toofff!

2020-09-27 07:27 UTC, merged