[WIP] Add reset password form
bolt/core pull request #1976
Opened 2020-10-09 19:48 UTC by LordSimal

## What does this PR improve?

This PR adds a form to request a "Reset my password" email which is linked on the login page.

![image](https://user-images.githubusercontent.com/9105243/95625152-5696aa80-0a78-11eb-993d-2a0f05e467bd.png)

![image](https://user-images.githubusercontent.com/9105243/95625201-6a421100-0a78-11eb-931e-0901f362da03.png)

After entering a valid registered email you should get an email with a reset password link. After clicking on that you should get:

![image](https://user-images.githubusercontent.com/9105243/95625395-b8efab00-0a78-11eb-969d-13022da415e4.png)

Now if you enter 2 identical "secure" passwords (see `src/Form/ChangePasswordFormType.php`) you should get back to the login form with a confirm message showing you, that the password has been reset.

![image](https://user-images.githubusercontent.com/9105243/95625666-23085000-0a79-11eb-9876-31ce76dd96e3.png)

## What did I do?

I basically ran `bin/console make:reset-password` and followed its instructions.

After that I adjusted all generated `templates/reset_password` templates to
- fit/use the bolt core base templates
- transform english text to translatable text

Also I added the ability to set specific configs via the `config/bolt/config.yaml`.

In there you can set the following settings:

```
reset_password_settings:
    mail_from: "do-not-reply@dummy.com"
    mail_name: "Bolt CMS"
    mail_subject: "Your password reset request"
    mail_template: "reset_password/email.html.twig"
```

Also to mention is the fact, that I didn't enable the "This email is not registered function" due to security reasons.
See the `'There was a problem handling your password reset request - %s',` line in the `src/Controller/ResetPasswordController.php`

## What is missing

Since I couldn't get my mail server to allow sending mails via the local environment I couldn't test the mail which should be sent to the user after a successful request.

Also I was not able to translate the text inside this email so I would be very happy if someone can help me there.

2020-10-12 17:26 UTC, bobdenotter requested changes

2020-10-12 17:26 UTC, bobdenotter commented on src/.preload.php
> +<?php
We don't need this file ^_^

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +     * @Route("", name="app_forgot_password_request")
```suggestion
     * @Route("", name="bolt_forgot_password_request")
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +            return $this->redirectToRoute('app_forgot_password_request');
```suggestion
            return $this->redirectToRoute('bolt_forgot_password_request');
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +            return $this->redirectToRoute('app_forgot_password_request');
```suggestion
            return $this->redirectToRoute('bolt_forgot_password_request');
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +     * @Route("/check-email", name="app_check_email")
```suggestion
     * @Route("/check-email", name="bolt_check_email")
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +     * @Route("/reset/{token}", name="app_reset_password")
```suggestion
     * @Route("/reset/{token}", name="bolt_reset_password")
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +            return $this->redirectToRoute('app_check_email');
```suggestion
            return $this->redirectToRoute('bolt_check_email');
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +        // Marks that you are allowed to see the app_check_email page.
```suggestion
        // Marks that you are allowed to see the bolt_check_email page.
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +            // the lines below and change the redirect to 'app_forgot_password_request'.
```suggestion
            // the lines below and change the redirect to 'bolt_forgot_password_request'.
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +            return $this->redirectToRoute('app_check_email');
```suggestion
            return $this->redirectToRoute('bolt_check_email');
```

2020-10-12 17:26 UTC, bobdenotter commented on src/Controller/ResetPasswordController.php
> +        return $this->redirectToRoute('app_check_email');
```suggestion
        return $this->redirectToRoute('bolt_check_email');
```

2020-10-12 17:26 UTC, bobdenotter commented on templates/reset_password/check_email.html.twig
> +                <p>{{ 'reset_password.check_email_sent_text_2'|trans({'%tryagain%': '<a href="' ~ path('app_forgot_password_request') ~ '">try again</a>' }) | raw }}</p>
```suggestion
                <p>{{ 'reset_password.check_email_sent_text_2'|trans({'%tryagain%': '<a href="' ~ path('bolt_forgot_password_request') ~ '">try again</a>' }) | raw }}</p>
```

2020-10-12 17:26 UTC, bobdenotter commented on templates/reset_password/email.html.twig
> +<a href="{{ url('app_reset_password', {token: resetToken.token}) }}">{{ url('app_reset_password', {token: resetToken.token}) }}</a>
```suggestion
<a href="{{ url('bolt_reset_password', {token: resetToken.token}) }}">{{ url('bolt_reset_password', {token: resetToken.token}) }}</a>
```

2020-10-12 17:26 UTC, bobdenotter commented on templates/reset_password/request.html.twig
> +{% endblock %}
```suggestion
{% endblock %}

```

2020-10-12 17:26 UTC, bobdenotter commented on templates/security/login.html.twig
> +                    <a href="{{ path('app_forgot_password_request') }}" class="btn btn-primary">
```suggestion
                    <a href="{{ path('bolt_forgot_password_request') }}" class="float-right btn btn-tertiary">
```

2020-10-12 17:26 UTC, bobdenotter commented on templates/reset_password/reset.html.twig
> +                <button class="btn btn-primary">{{ 'reset_password.reset_btn'|trans }}</button>
```suggestion
                <button class="float-right btn btn-tertiary">{{ 'reset_password.reset_btn'|trans }}</button>
```

2020-10-12 17:27 UTC, bobdenotter commented
I've fixed some low-hanging fruit. Mainly updating the name of the routes. 

We'll need to ensure that we tell people who're upgrading to run the following:

```
bin/console do:sc:up --force
```

For some reason it's not sending emails on my test-server either. Even though I have SMTP set up. I'm going to dig in some more.

2020-10-12 17:29 UTC, bobdenotter commented on templates/reset_password/request.html.twig
> +                <a href="{{ path('bolt_login') }}" class="btn btn-primary">
```suggestion
                <a href="{{ path('bolt_login') }}" class="float-right btn btn-tertiary">
```

2020-10-12 17:46 UTC, LordSimal commented on src/.preload.php
> +<?php
👍 has been deleted

2020-10-12 17:46 UTC, LordSimal commented on src/Controller/ResetPasswordController.php
> +     * @Route("", name="app_forgot_password_request")
changed that 👍

2020-10-12 17:46 UTC, LordSimal commented on src/Controller/ResetPasswordController.php
> +            return $this->redirectToRoute('app_forgot_password_request');
changed that 👍

2020-10-12 17:59 UTC, LordSimal commented on src/Controller/ResetPasswordController.php
> +            return $this->redirectToRoute('app_forgot_password_request');
changed that 👍

2020-10-12 17:59 UTC, LordSimal commented on src/Controller/ResetPasswordController.php
> +     * @Route("/check-email", name="app_check_email")
changed that 👍

2020-10-12 17:59 UTC, LordSimal commented on src/Controller/ResetPasswordController.php
> +        return $this->redirectToRoute('app_check_email');
changed that 👍

2020-10-12 17:59 UTC, LordSimal commented on templates/reset_password/check_email.html.twig
> +                <p>{{ 'reset_password.check_email_sent_text_2'|trans({'%tryagain%': '<a href="' ~ path('app_forgot_password_request') ~ '">try again</a>' }) | raw }}</p>
changed that 👍

2020-10-12 18:00 UTC, LordSimal commented on templates/reset_password/reset.html.twig
> +                <button class="btn btn-primary">{{ 'reset_password.reset_btn'|trans }}</button>
changed that 👍

2020-10-12 18:01 UTC, LordSimal commented on templates/reset_password/request.html.twig
> +                <a href="{{ path('bolt_login') }}" class="btn btn-primary">
changed that 👍

2020-10-12 18:05 UTC, LordSimal commented on templates/reset_password/request.html.twig
> +{% endblock %}
yes my lord 🙇 😄

2020-10-12 18:08 UTC, LordSimal commented
- Fixed all app_ routes and changed them to bolt_ routes.
- Added missing translation for E-Mail template

2020-10-13 12:23 UTC, I-Valchev commented
@LordSimal @bobdenotter wohoo, finally a password reset feature 🥳

This may be coming in too late, but afaik so far we've not used Symfony forms in core, insteading building the frontend forms with html/twig, e.g. if i look at `login.html.twig`.

For consistency, would it be better to do that too?

2020-10-13 13:35 UTC, LordSimal commented
@I-Valchev so instead of building forms like
```
{{ form_start(requestForm, {'attr': {'class': 'reset-password__form'}}) }}
{{ form_row(requestForm.email) }}
...
{{ form_end(requestForm) }}
```

you would like to built it like 

```
<form action="{{ path('bolt_login') }}" method="post" class="" id="login-form">
    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}"/>
    {% include '@bolt/_partials/fields/text.html.twig' with {
        'label' : 'label.username_or_email'|trans,
        'name' : 'username',
        'value' : last_username,
        'disabled' : false,
        'placeholder': 'placeholder.username_or_email'|trans,
        'autofocus': true,
    } %}
</form>
```

and therefore have more control over the form, or am I wrong?

2020-10-13 13:47 UTC, I-Valchev commented
@LordSimal exactly 😅

In that case, do we need `ChangePasswordFormType.php`?

2020-10-14 09:51 UTC, bobdenotter commented
@LordSimal @I-Valchev Yes, I mostly agree. For long-term maintainability it'd be good if we use the same way of constructing our forms throughout.

On the other hand, this _is_ the de-facto symfony way, and we should perhaps consider moving other forms that are _not_ "Edit Content" as well. Like, 'login', and 'edit profile'. 

So, yeah, i'm a bit conflicted if we should ask @LordSimal to refactor this PR, or if we should add a TODO item for some of those other ones in core right now.. 🤔

2020-10-14 10:21 UTC, LordSimal commented
I haven't looked so deeply into the Bolt Core yet but how many "internal" forms are built without Symfony Forms?

2020-10-14 11:27 UTC, bobdenotter commented
From the top of my head: 

 - Login
 - Reset password
 - Edit (own) profile
 - Add / Edit user
 - Edit Content (should remain as-is)
 - Edit Media 
 - Edit Configuration / Template / Text files (basically just a CodeMirror instance)
 
Out of scope, imho:  
 - API explorer (straight from API Platform)
 - Translations (Straight from PHPTranslate)
 - And there's a few loose 'search', 'filter', etc inputs, that aren't "real" forms.

2020-10-14 13:27 UTC, bobdenotter commented
After giving this some more thought, with @I-Valchev, i think we should keep this as-is. 

Let's instead see if we can migrate some of the "non SF-forms" forms to SF-forms as well, instead. (as separate PR's / tasks)

2020-10-14 13:33 UTC, LordSimal commented
well then I will first try to do that with the login form (in a separate PR as you said)

2020-10-14 14:57 UTC, bobdenotter approved these changes
I'm going to merge this in to the `feature/reset-password` branch. That way we can test it properly, in order to include it in the 4.2 release!

2020-10-14 14:57 UTC, merged

2021-07-31 18:36 UTC, LordSimal commented
Just wanted to remind @bobdenotter that this feature still is out there waiting to be released 😉  
Just noticed it when installing 4.2 that its not there 😭