Show 'quick links' to taxonomies in the sidebar of listings
bolt/core pull request #2147
Opened 2020-11-18 17:20 UTC by bobdenotter

See screenshot: 

![Screenshot 2020-11-18 at 18 19 40](https://user-images.githubusercontent.com/1833361/99564396-ae56f880-29ca-11eb-83fa-d9ce83364e2f.png)

2020-11-22 15:16 UTC, bobdenotter commented on templates/content/listing.html.twig
> +                                {% if taxonomyDefinition.behaves_like != 'tags' %}
```suggestion
                                {% if taxonomyDefinition and taxonomyDefinition.behaves_like != 'tags' %}
```

2020-11-24 08:23 UTC, I-Valchev requested changes
@bobdenotter Were you going to make this so that the `Clear filter` button is visible when filtering on the taxonomies?

2020-11-24 08:25 UTC, bobdenotter commented
Ah, yes! I _am_ going to do that!

2020-12-01 14:35 UTC, bobdenotter commented
Tweaked and rebased!

2020-12-01 14:57 UTC, I-Valchev approved these changes
Me likes! 😇

Let's roll with it.

2020-12-01 14:57 UTC, merged