`ROLE_ADMIN` can access site in maintenance mode
bolt/core pull request #2376
Opened 2021-02-08 16:07 UTC by I-Valchev

Fixes #1883 in the master branch, due to the new permissions feature.

2021-02-08 16:32 UTC, bobdenotter requested changes
If we merge this in as-is, we're definitely going to have confused users.. An admin user might have the site on maintenance mode, they forget about it (because *they* can see the site), only to find out that other people can't. 

We should make it _visible_ that the site is in maintenance.. Perhaps add another `snippet` widget that 'll output a warning?

2021-02-08 16:40 UTC, bobdenotter commented
Like this? ;-) 

![fhBnpx2DZT](https://user-images.githubusercontent.com/1833361/107251515-b73cf080-6a34-11eb-9d59-a36630430de4.gif)

2021-02-08 19:39 UTC, I-Valchev commented
@bobdenotter I DOOOO. Let's add it!!

![Alt Text](https://media.giphy.com/media/kZiDpAW9d9fr2suuS7/giphy-downsized.gif)

2021-02-09 08:28 UTC, bobdenotter commented
Here's some HTML and CSS:

```
<style>
  #bolt-maintenance-notice {
    border: 1px solid #F00;
    position: absolute;
    background-color: white;
    color: #F00;
    top: 100px;
    left: -100px;
    width: 450px;
    transform: rotateY(0deg) rotate(-45deg);
    box-shadow: 2px 0 15px rgba(0, 0, 0, 0.5);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
    font-size: 16px;
    font-weight: bold;
    line-height: 24px;
    padding: 8px;
  }
</style>

<div id='bolt-maintenance-notice'>
  <marquee>🚨 Maintenance mode is activated 🚨 Maintenance mode is activated 🚨 Maintenance mode is activated 🚨 Maintenance mode is activated 🚨 </marquee>
</div>
```

2021-02-09 09:16 UTC, I-Valchev commented
![image](https://user-images.githubusercontent.com/7093518/107341930-e64c7400-6abf-11eb-9baa-501e4dfa0b27.png)

2021-02-09 13:09 UTC, bobdenotter requested changes
We shouldn't be modifying these `id`s in the translation files.

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="f8zXapF" name="form.empty_email">
```suggestion
    <unit id="o2f3RiO" name="form.empty_email">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="dp42qbF" name="reset_password.email_title">
```suggestion
    <unit id="3prMgfK" name="reset_password.email_title">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="xS2vvXw" name="reset_password.email_description">
```suggestion
    <unit id="oaRkfvE" name="reset_password.email_description">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="apkSD11" name="reset_password.email_expire">
```suggestion
    <unit id="Afb4dal" name="reset_password.email_expire">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="_gg3hPE" name="reset_password.email_thanks">
```suggestion
    <unit id="9ga3FlV" name="reset_password.email_thanks">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="harDiJR" name="reset_password.enter_pwd">
```suggestion
    <unit id="7d24Grt" name="reset_password.enter_pwd">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="rU9cSfq" name="label.repeat_password">
```suggestion
    <unit id="a2f1pra" name="label.repeat_password">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="Tg5zdeo" name="reset_password.not_matching_pwds">
```suggestion
    <unit id="2f19Gat" name="reset_password.not_matching_pwds">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="1JZeWxG" name="reset_password.minimum_length">
```suggestion
    <unit id="2ahb7da" name="reset_password.minimum_length">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="GUQYLn2" name="reset_password.no_token">
```suggestion
    <unit id="a3frsl4" name="reset_password.no_token">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="SjuOnue" name="reset_password.reset_successful">
```suggestion
    <unit id="hsg341k" name="reset_password.reset_successful">
```

2021-02-09 13:09 UTC, bobdenotter commented on translations/messages.en.xlf
> +    <unit id="5Xr92sQ" name="reset_password.problem_with_request">
```suggestion
    <unit id="7f2x41k" name="reset_password.problem_with_request">
```

2021-02-09 13:11 UTC, bobdenotter approved these changes

2021-02-11 14:46 UTC, merged