#2429 Fix some accessibility issues
bolt/core pull request #2592
Opened 2021-05-19 15:28 UTC by DorienD

- Add correct ID's to fields
- Change color of code to be contrast compliant
- Remove space from aria-selected
- And some more minor changes

2021-05-20 13:00 UTC, I-Valchev requested changes
Hey @DorienD ,

Thanks a lot for the PR! Looking good!

One question: it seems like there are already translated labels for the 4 items here. https://github.com/bolt/core/blob/master/translations/messages.en.xlf

Am I overlooking something, or the changes to `translations/messages.en.xlf` are not needed?

2021-05-21 07:23 UTC, DorienD commented
I will look into this.

2021-05-25 08:52 UTC, DorienD commented on translations/messages.en.xlf
> +      <segment>
@I-Valchev I can't really figure out why it thinks I Added this translation. But its still the same as on master, so I guess it's ok?

2021-05-25 08:52 UTC, DorienD commented
@I-Valchev Fixed it, can you check it again :)

2021-05-25 11:19 UTC, I-Valchev approved these changes
@DorienD awesome, thanks! Sometimes GitHub is being a little weird with those differences, let's merge it in as it is. I'll check if it is duplicated and remove it afterwards, if necessary.

Thanks for fixing these accessibility issues 👍

2021-05-25 11:27 UTC, mcdennem approved these changes

2021-05-25 11:51 UTC, merged