Allow `GET` requests for Preview
bolt/core pull request #2904
Opened 2021-11-03 12:02 UTC by bobdenotter

Sometimes clients or editors paste links to specific pages with a URL they've copy/pasted from a preview. Like `https://example.org/preview/123`. 

This will give an error like: 

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/1833361/140055210-4fe81001-b716-4d9b-b13c-e51f3736a4b7.png">

This PR allows a `GET` request to that page (assuming it's published, similar to the existing "detail view")

2021-11-03 12:36 UTC, nestordedios approved these changes
Nice fix! Looks good 👍

2021-11-05 09:00 UTC, I-Valchev requested changes
I like the idea of fixing that scary error screen... but I'm not sure if rendering the saved version for a preview link is the way to go.

If somebody copies the preview and shares it, they'd expect the unsaved changes to be shown, which we can't do.

Perhaps we could either show a nicer error/explanation why sharing the preview does not work that way, or redirecting to the backend 🤔

2021-11-08 12:10 UTC, bobdenotter commented
The thing is, the people grabbing these links and sharing them will not see this nicer error, because it already works _for them_. it only breaks for the people _receiving_ the link, and i don't think they'll benefit from a link to the backend.. 

On the other hand, if we redirect it to the correct "Edit" page for that record.. At least you'd end up in the correct spot without having to dig much deeper. Would that be a good compromise? 🤔

2021-11-08 14:15 UTC, I-Valchev commented
@bobdenotter yes, that would make sense! Sure, I'm on board 🚂 🚋 🚋

2021-11-08 14:32 UTC, bobdenotter commented
@I-Valchev Updated!

2021-11-09 08:16 UTC, I-Valchev approved these changes
👍 Yesss, looks good! Let's roll.

2021-11-09 13:37 UTC, merged